# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sk085-my-app
#   namespace: skala-practice
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sk085-my-app
#   template:
#     metadata:
#       annotations:
#         prometheus.io/scrape: 'true'
#         prometheus.io/port: '8081'
#         prometheus.io/path: '/actuator/prometheus'
#         update: 0af454217f8bbbe171183e64c690dbb4
#       labels:
#         app: sk085-my-app
#     spec:
#       serviceAccountName: default
#       containers:
#       - name: my-app
#         image: amdp-registry.skala-ai.com/skala25a/sk085-my-app:1.0.0
#         imagePullPolicy: Always
#         env:
#         - name: LOGGING_LEVEL
#           value: DEBUG
#         - name: USER_NAME
#           value: sk085
#         - name: NAMESPACE
#           value: skala-practice
#         - name: SPRING_PROFILES_ACTIVE
#           value: prod
#         - name: SPRING_DATASOURCE_URL
#           valueFrom:
#             configMapKeyRef:
#               name: sk085-my-app-config
#               key: SPRING_DATASOURCE_URL
#         - name: SPRING_DATASOURCE_USERNAME
#           valueFrom:
#             configMapKeyRef:
#               name: sk085-my-app-config
#               key: SPRING_DATASOURCE_USERNAME
#         envFrom:
#         - secretRef:
#             name: sk085-my-app-secrets

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk085-my-app
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk085-my-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 0af454217f8bbbe171183e64c690dbb4
      labels:
        app: sk085-my-app
    spec:
      serviceAccountName: default
      containers:
      - name: my-app
        image: amdp-registry.skala-ai.com/skala25a/sk085-my-app:2.0.0
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk085
        - name: NAMESPACE
          value: skala-practice
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: sk000-my-app-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sk000-my-app-config
              key: SPRING_DATASOURCE_USERNAME
        envFrom:
        - secretRef:
            name: sk000-my-app-secrets